menuwatch/urls.py
from django.contrib import admin
from django.conf.urls import patterns, include, url
from apps.menus import views as menu_views

# See: https://docs.djangoproject.com/en/dev/ref/contrib/admin/#hooking-adminsite-instances-into-your-urlconf
admin.autodiscover()


# See: https://docs.djangoproject.com/en/dev/topics/http/urls/
urlpatterns = patterns(
    '',

    # Admin panel and documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),

    # Menu views
    url(r'^$', menu_views.IndexView, name='index'),
    url(r'^about', menu_views.AboutView, name='about'),
    url(r'^login', menu_views.LoginView, name='login'),
    url(r'^logout', menu_views.LogoutView, name='logout'),
    url(r'^signup', menu_views.SignupView, name='signup'),
    url(r'^verify', menu_views.VerifyView, name='verify'),
    url(r'^reset', menu_views.RequestResetView, name='reset'),
    url(r'^account?/$', menu_views.AccountView, name='account'),
    url(r'^account/password/change', menu_views.ChangePasswordView, name='chpwd'),
    url(r'^account/password/reset', menu_views.ResetPasswordView, name='rspwd'),
    url(r'^browse', menu_views.BrowseView, name='browse'),
    url(r'^upgrade', menu_views.UpgradeView, name='upgrade'),
    url(r'^payment', menu_views.PaymentView, name='payment'),
    url(r'^exclude', menu_views.ExcludeView, name='exclude'),
    url(r'^unsubscribe', menu_views.UnsubView, name='unsub'),
    url(r'^getready', menu_views.GetReadyView, name='getready'),

    url(r'^api/add', menu_views.AddView, name='add'),
    url(r'^api/delete', menu_views.DeleteView, name='delete'),
    url(r'^api/settings', menu_views.SettingsView, name='settings'),

    url(r'^debug/email', menu_views.DebugEmailView, name='debugemail'),
    url(r'^debug/onboard', menu_views.OnboardView, name='onboard'),
)

menuwatch/apps/menus/forms.py
from django import forms
from django.contrib.auth.models import User
from django.utils.safestring import mark_safe
import re

class SignupForm(forms.Form):
    fname = forms.CharField(max_length=50,widget=forms.TextInput(attrs={'placeholder': 'First name'}))
    lname = forms.CharField(max_length=50,widget=forms.TextInput(attrs={'placeholder': 'Last name'}))
    email = forms.EmailField(max_length=50,widget=forms.TextInput(attrs={'placeholder': 'Email'}))
    pword1 = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Password'}))
    pword2 = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Password, again'}))

    def clean_pword1(self):
        pword1 = self.cleaned_data.get('pword1')
        if len(pword1) < 6:
            raise forms.ValidationError("Your password must be at least six characters")
        return pword1

    def clean_pword2(self):
        pword1 = self.cleaned_data.get('pword1')
        pword2 = self.cleaned_data.get('pword2')

        if pword1 != pword2:
            raise forms.ValidationError("Passwords do not match")
        return pword2

    def clean_email(self):
        email = self.cleaned_data.get('email').lower()
        if User.objects.filter(email = email).count():
            raise forms.ValidationError(mark_safe('A user with this email already exists. Did you mean to <a href="/login">login</a>, or to <a href="/reset">reset your password</a>?'))
        return email


class LoginForm(forms.Form):
    email = forms.EmailField(max_length=50,widget=forms.TextInput(attrs={'placeholder': 'Email'}))
    pword = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Password'}))

    def clean_email(self):
        email = self.cleaned_data.get('email').lower()
        if not User.objects.filter(email = email).count():
            raise forms.ValidationError(mark_safe('We don\'t have any users with that email address. Did you mean to <a href="/signup">sign up</a>?'))
        return email

    def clean_pword(self):
        email = self.cleaned_data.get('email')
        pword = self.cleaned_data.get('pword')
        if User.objects.filter(email = email).count() == 1:
            u = User.objects.filter(email = email)[:1].get()
            if not u.check_password(pword):
                raise forms.ValidationError(mark_safe('Incorrect password. If you forgot, you can request a <a href="/reset">password reset</a>.'))
        return pword


class RequestResetForm(forms.Form):
    email = forms.EmailField(max_length=50,widget=forms.TextInput(attrs={'placeholder': 'Email'}))

    def clean_email(self):
        email = self.cleaned_data.get('email').lower()
        if not User.objects.filter(email = email).count():
            raise forms.ValidationError(mark_safe('We don\'t have any users with that email address. <a href="/signup">Sign up</a> for a new account?'))
        return email


class ProcessResetForm(forms.Form):
    pword1 = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'New password'}))
    pword2 = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'New password, again'}))

    def clean_pword1(self):
        pword1 = self.cleaned_data.get('pword1')
        if len(pword1) < 6:
            raise forms.ValidationError("Your password must be at least six characters")
        return pword1

    def clean_pword2(self):
        pword1 = self.cleaned_data.get('pword1')
        pword2 = self.cleaned_data.get('pword2')

        if pword1 != pword2:
            raise forms.ValidationError("Passwords do not match")
        return pword2

class ChangePasswordForm(forms.Form):
    pword0 = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Old password'}))
    pword1 = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'New password'}))
    pword2 = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'New password, again'}))

    def __init__(self, user, *args, **kwargs):
        self.user = user
        super(ChangePasswordForm, self).__init__(*args, **kwargs)

    def clean_pword0(self):
        pword0 = self.cleaned_data.get('pword0')
        if not self.user.check_password(pword0):
            raise forms.ValidationError("Incorrect old password")
        return pword0

    def clean_pword1(self):
        pword1 = self.cleaned_data.get('pword1')
        if len(pword1) < 6:
            raise forms.ValidationError("Your password must be at least six characters")
        return pword1

    def clean_pword2(self):
        pword1 = self.cleaned_data.get('pword1')
        pword2 = self.cleaned_data.get('pword2')

        if pword1 != pword2:
            raise forms.ValidationError("Passwords do not match")
        return pword2

menuwatch/apps/menus/views.py
from django.contrib.auth.models import User
from django.contrib.auth import login, logout, authenticate
from django.views.decorators.cache import never_cache
from django.views.decorators.csrf import csrf_exempt
from django.core.mail import EmailMultiAlternatives
from django.http import HttpResponseRedirect, HttpResponse
from django.template import loader
from django.shortcuts import render, render_to_response
from apps.menus import forms
from apps.menus import models as menumods
from random import randint
from hashlib import md5
from urllib import urlencode
import stripe
import uuid
import re


##################
## SIMPLE VIEWS ##
##################

def ExcludeView(request):
    return render(request, 'menus/exclude.html')


def AboutView(request):
    return render(request, 'menus/about.html')


def BlockView(request):
    return render(request, 'menus/block.html')

def GetReadyView(request):
    return render(request, 'menus/getready.html')


################
## MAIN VIEWS ##
################

def IndexView(request):
    photo_num = randint(0,4)
    photo = str(photo_num)+".jpg"
    
    # YEAHHH I know, I'm storing data in a view. Sue me.
    # Also this is a fairly strange way to work around python's lack of switch statements
    # All in all, not one of the best code blocks I've ever written

    credits = {
        0: ("flic.kr/pinksherbet", "http://www.flickr.com/photos/pinksherbet/2316123291/"),
        1: ("flic.kr/ginnerobot", "http://www.flickr.com/photos/ginnerobot/2523448766/"),
        2: ("flic.kr/nomadic_lass", "http://www.flickr.com/photos/nomadic_lass/5846658416/"),
        3: ("flic.kr/giovannijl-s_photohut", "http://www.flickr.com/photos/giovannijl-s_photohut/459381964/"),
        4: ("flic.kr/clarity", "http://www.flickr.com/photos/clairity/1328402515/"),
    }

    name, link = credits.get(photo_num, (None,  None))
    
    return render(request, 'menus/index.html', {
        "photo": photo,
        "name": name,
        "link": link,
        "signedin": request.user.is_authenticated(),
    })


def BrowseView(request):
    if request.user.is_authenticated():
        profile = menumods.Profile.objects.get(user__exact=int(request.user.pk))
        if profile.onboarded:
            if 'sort' in request.GET and request.GET['sort'] == 'popular':
                context = {
                    "tab": "popular",
                    "foodlist": sorted(menumods.Food.objects.all(), key=lambda x: x.num_watches(), reverse=True)[:40]
                }
            elif 'sort' in request.GET and request.GET['sort'] == 'recent':
                context = {
                    "tab": "recent",
                    "foodlist": sorted(menumods.Food.objects.exclude(last_date=None), key=lambda x: x.last_date.date, reverse=True)[:40]
                }
            elif 'sort' in request.GET and request.GET['sort'] == 'search' and 'query' in request.GET:
                foods = sorted(menumods.Food.objects.exclude(next_dates=None).filter(name__icontains=request.GET['query']), key=lambda x: x.peek_next_date())
                if len(foods) == 0:
                    foods = None
                context = {
                    "tab": "searchresults",
                    "searchstr": request.GET['query'],
                    "foodlist": foods
                } 
            elif 'sort' in request.GET and request.GET['sort'] == 'search':
                context = {
                    "tab": "search",
                    "foodlist": None
                }
            else:
                context = {
                    "tab": "upcoming",
                    "foodlist": sorted(menumods.Food.objects.exclude(next_dates=None), key=lambda x: x.peek_next_date())[:40]
                }
            return render(request, 'menus/browse.html', context)
        else:
            profile.onboarded = True
            profile.save()
            context = {
                # get five foods coming up in the next two weeks
                "popular": sorted(menumods.Food.objects.exclude(next_dates=None), key=lambda x: x.num_watches(), reverse=True)[:5]
            }
            return render(request, 'menus/onboard.html', context)

    else:
        return HttpResponseRedirect('/login?next=browse')



##########################
## AUTHENTICATION VIEWS ##
##########################

def LoginView(request):
    if request.user.is_authenticated():
        return HttpResponseRedirect('/browse')
    else:
        if request.method == 'POST':
            try:
                redirect = re.search('(?:next=)(.+)', request.META.get('HTTP_REFERER')).group(1)
            except:
                redirect = "browse"
            
            form = forms.LoginForm(request.POST)

            if form.is_valid():  # All validation rules pass
                email = form.cleaned_data['email']
                pword = form.cleaned_data['pword']
                user = authenticate(username=email, password=pword)
                if user is not None and user.is_active:
                    login(request, user)
                    return HttpResponseRedirect('/'+redirect)
                else:
                    return HttpResponseRedirect('/login?next='+redirect)

            email = None  # don't try to auto-fill if the form was invalid

        else:
            form = forms.LoginForm()  # An unbound form

            if request.GET.get('e') is not None:
                email = request.GET.get('e')
            else:
                email = None

        context = {
            'form': form,
            'action': 'login',
            'email': email,
        }

        if 'HTTP_HOST' in request.META and re.search('herokuapp', request.META['HTTP_HOST']):
            context['reverify'] = True

        return render(request, 'menus/auth.html', context)


def LogoutView(request):
    if request.user.is_authenticated():
        logout(request)
    return HttpResponseRedirect('/')


def SignupView(request):
    def send_verify_mail(request, new_user):
        context = {
            'first_name': new_user.first_name,
            'verify_link': "http://menuwatch.bjacobel.com/verify?" + urlencode({'e':new_user.email, 'v':md5(new_user.email).hexdigest()}),
            'unsubscribe_link': urlencode({'u':new_user.email, 't':md5(new_user.date_joined.isoformat()).hexdigest()}),
            'email_type': 'verify',
        }
        msg = EmailMultiAlternatives(
            "Menuwatch Signup Confirmation",
            "Hi, {}! Please visit this URL to finish setting up your account. {}".format(context['first_name'], context['verify_link']),
            "Menuwatch <mail@menuwatch.bjacobel.com>",
            ["{} {} <{}>".format(new_user.first_name, new_user.last_name, new_user.email),],
        )
        msg.attach_alternative(render_to_response('menus/email.html', context).content, "text/html")
        msg.send()

    if request.user.is_authenticated():
        return HttpResponseRedirect('/browse')
    else:
        if request.method == 'POST':  # If the form has been submitted...
            form = forms.SignupForm(request.POST)  # A form bound to the POST data
            if form.is_valid():  # All validation rules pass
                email = form.cleaned_data['email']
                fname = form.cleaned_data['fname'].capitalize()
                lname = form.cleaned_data['lname'].capitalize()
                pword = form.cleaned_data['pword1']
                new_user = User.objects.create_user(email, email, pword)
                new_user.first_name = fname
                new_user.last_name = lname
                new_user.is_active = False
                new_user.save()
                profile = menumods.Profile.objects.create(user_id=new_user.pk)
                profile.save()
                send_verify_mail(request, new_user)
                return HttpResponseRedirect('/getready')  # Redirect after POST
        else:
            form = forms.SignupForm()  # An unbound form

        return render(request, 'menus/auth.html', {
            'form': form,
            'action': 'signup',
        })


def VerifyView(request):
    if request.user.is_authenticated():
        return HttpResponseRedirect('/browse')
    elif request.GET and 'e' in request.GET and 'v' in request.GET:
        email = request.GET['e']
        emailhash = request.GET['v']
        if md5(email).hexdigest() == emailhash:
            to_verify = User.objects.get(username__exact=email)
            to_verify.is_active=True
            to_verify.save()
            return HttpResponseRedirect('/login?{}'.format(urlencode({'e':email})))
    else:
        return render(request, '500.html')


def RequestResetView(request):
    def send_reset_mail(request, dumb_user, newpass):
        context = {
            'first_name': dumb_user.first_name,
            'reset_link': "http://menuwatch.bjacobel.com/account/password/reset?" + urlencode({'e':dumb_user.email, 'p':newpass}),
            'unsubscribe_link': urlencode({'u':dumb_user.email, 't':md5(dumb_user.date_joined.isoformat()).hexdigest()}),
            'email_type': 'reset',
        }
        msg = EmailMultiAlternatives(
            "Menuwatch Password Reset",
            "Hi, {}! A password reset was just requested for this account.\n\nIf you didn't request a password reset, simply delete this email. If you would like to reset your password, please click below. {}".format(context['first_name'], context['reset_link']),
            "Menuwatch <mail@menuwatch.bjacobel.com>",
            ["{} {} <{}>".format(dumb_user.first_name, dumb_user.last_name, dumb_user.email),],
        )
        msg.attach_alternative(render_to_response('menus/email.html', context).content, "text/html")
        msg.send()

    if request.user.is_authenticated():
        return HttpResponseRedirect('/account/password/change')
    else:
        if request.method == 'POST':      
            form = forms.RequestResetForm(request.POST)

menuwatch/templates/menus/account.html
{% extends "menus/base.html" %}

{% block body %}
    <div class="container lato">
        <h1 class="lato">Account Management</h1>
        <h2 class="lato">{{ profile.fullname }} <span class="narrow">({{ profile.email }})</span></h2>
        <div class-"container account-fields">
            <div class="col-xs-12 col-sm-4 account-field">
                <h3 class="account-field-header lato narrow">SETTINGS</h3>
                <h4 class="lato">Email frequency:<i data-title="<h4>Email frequency</h4>" data-content="<h5><strong>Weekly:</strong> Get just one email every Sunday with all your alerts for that week.<br/><br/><strong>Every Few:</strong> Get emails on Sunday, Wednesday and Friday mornings with the next few days' alerts.<br/><br/><strong>Daily:</strong> Get emails every morning with your alerts for the day.</h5>" class="left-spacer icon-question-sign"></i></h4>
                <div class="btn-group setting-group" setting="frequency">
                    <button id="1" type="button" class="btn btn-default">Weekly</button>
                    <button id="3" type="button" class="btn btn-default">Every few days</button>
                    <button id="7" type="button" class="btn btn-default">Daily</button>
                </div>
                <h4 class="lato">Locations:<i data-title="<h4>Locations</h4>" data-content="<h5><strong>Both:</strong> Get alerts for foods at both dining halls.<br/><br/><strong>Moulton:</strong> Get alerts only for foods at Moulton Union.<br/><br/><strong>Thorne:</strong> Get alerts only for foods at Thorne.</h5>" class="left-spacer icon-question-sign"></i></h4>
                <div class="btn-group setting-group" setting="locations">
                    <button id="1" type="button" class="btn btn-default">Both</button>
                    <button id="2" type="button" class="btn btn-default">Moulton</button>
                    <button id="3" type="button" class="btn btn-default">Thorne</button>
                </div>
                <h4 class="lato">Password: <a href="/account/password/change">Change<i class="icon-caret-right"></i></a></h4>
                <h4 class="lato"><a class="del-account" href="#">Delete account<i class="icon-caret-right"></i></a></h4>
            </div>
            <div class="col-xs-12 col-sm-4 account-field">
                <h3 class="account-field-header lato narrow">PRO</h3>
                {% if profile.pro %}
                    <h4 class="lato">Pro account enabled! Enjoy unlimited watches.</h4>
                {% else %}
                    <h4 class="lato">You're on a basic account, with {{ profile.used_watches }} of your 10 watches used. <a href="/upgrade">Upgrade now <i class="icon-caret-right"></i></a></h4>
                {% endif %}
            </div>
            <div class="col-xs-12 col-sm-4 account-field">
                <h3 class="account-field-header lato narrow">WATCHES</h3>
                <ul class="lato watch-list">
                    {% for watch in profile.my_watches %}
                        <li class="watch-row"><h4 class="lato">{{ watch.foodname }}</h4><h4 class="right api delete" data="{{ watch.food.pk }}"><i class="icon-remove"></i></h4></li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
    <div class="modal fade" id="deleteModal">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title">Warning!</h4>
                </div>
                <div class="modal-body">
                    <p>Are you sure you want to delete your account? This cannot be undone.</p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                    <button type="button" class="btn btn-danger" onclick="window.location.href='/unsubscribe?{{ unsub_link }}'">DELETE ACCOUNT</button>
                </div>
            </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->
{% endblock %}

{% block footer_scripts %}
    {% include 'menus/api.html' %}
    <script>
        // setup popovers
        $("h4 i.icon-question-sign").popover({"html":"true"});
        
        // setup modal
        $(".del-account").click(function(){
            $('#deleteModal').modal();
        });

        // setup display of active setting
        $(".setting-group").each(function(){
            if($(this).attr("setting") == "frequency") {
                currSetting = "{{ profile.frequency }}";
            } else if ($(this).attr("setting") == "locations") {
                currSetting = "{{ profile.locations }}";
            }
            $("button", $(this)).each(function(){
                if($(this).attr("id") == currSetting){
                    $(this).removeClass("btn-default");
                    $(this).addClass("btn-primary");
                }
            });
        });

        // this only needs to run on this page so I'm just going to leave it inline here
        // fuck best practices, we'll do it live
        $(".setting-group button").click(function() {
            $newChoice = $(this);
            $.ajax({
                data: {
                    "setting_name": $newChoice.parent().attr("setting"),
                    "setting_value": $newChoice.attr("id")
                },
                type: 'post',
                url: '/api/settings',
                success: function(response) {
                    $(".btn-primary", $newChoice.parent()).removeClass("btn-primary").addClass("btn-default"); //oh jquery, you lovable clusterfuck
                    $newChoice.addClass("btn-primary");
                },
                error: function(xhr, ajaxOptions, thrownError) {
                }
            });
        });
    </script>
{% endblock %}

menuwatch/templates/menus/auth.html
{% extends "menus/base.html" %}

{% block body %}
<div class="shim"></div>
<div class="auth-box">
    {% if reverify %}
        <p class='lato'>Please verify your account details before continuing.</p>
    {% endif %}
    {% if action == "reset" %}
        <p class='lato'>A password reset email will be sent to the address below.</p>
    {% elif action == "account/password/reset" %}
        <p class='lato'>Password reset request successful. Please pick a new one.</p>
    {% endif %}
    <form class="auth-form" action="/{{ action }}" method="post">{% csrf_token %}
        {{ form.non_field_errors }}
        {% for field in form %}
            <div class="field-wrapper lato bold">
                {{ field }}
                {% if field.errors %}
                    <ul>
                        {% for error in field.errors %}
                            <li><i class="icon-warning-sign">  </i>{{ error }}</li>
                        {% endfor %}
                    </ul>
                {% endif %}
            </div>
        {% endfor %}
        {% if action == "login" %}
            <p class="cta active-button auth-action-wrapper">
                <input class="auth-action lato cta-text" type="submit" value="LOG IN"/>
                <i class="icon-chevron-right pointer"></i>
            </p>
            <p class="lato text-center">Don't have an account yet? <a href="/signup">Sign up!</a></p>
        {% elif action == "signup" %}
            <p class="cta active-button auth-action-wrapper">
                <input class="auth-action lato cta-text" type="submit" value="SIGN UP"/>
                <i class="icon-chevron-right pointer"></i>
            </p>
            <p class="lato text-center">(or, did you mean to <a href="/login">log in</a>?)</p>
        {% elif action == "account/password/change" %}
            <p class="cta active-button auth-action-wrapper">
                <input class="auth-action lato cta-text" type="submit" value="CHANGE"/>
                <i class="icon-chevron-right pointer"></i>
            </p>
        {% elif action == "account/password/reset" %} {# this is to pick a new pword after you've reset #}
            <p class="cta active-button auth-action-wrapper">
                <input class="auth-action lato cta-text" type="submit" value="FINISH"/>
                <i class="icon-chevron-right pointer"></i>
            </p>
        {% elif action == "reset" %} {# this is to ask for a reset #}
            <p class="cta active-button auth-action-wrapper">
                <input class="auth-action lato cta-text" type="submit" value="RESET"/>
                <i class="icon-chevron-right pointer"></i>
            </p>
        {% endif %}
    </form>
</div>
<div class="shim"></div>
<script>
    $(".shim").css("height", ($(window).height()-100-$(".navbar").height()-$(".auth-box").height())/2);
</script>
{% endblock %}

{% block footer_scripts %}
    {% if email != None %}
        <script type="text/javascript">
            $(document).ready(function(){
                $("#id_email").val("{{ email }}");
                $("#id_pword").focus();
            });
        </script>
    {% endif %}
{% endblock %}

menuwatch/templates/menus/block.html
{% extends "menus/base.html" %}

{% block body %}
    <div class="container">
        <a class="about-header" href="/">{% include "menus/includes/logo.html" %}</a>
        <h3 class="lato text-center" style="max-width:700px;margin:0 auto">
            Menuwatch is still under construction. We expect to launch in the first several weeks of the fall semester.
            <br/><br/><br/>
            If you want to get a head start, email <a href="mailto:bjacobel@gmail.com">Brian</a> and he'll get you set up as a beta tester. Otherwise - see you soon!
        </h3>
    </div>
{% endblock %}

{% block footer_scripts %}

{% endblock %}

menuwatch/templates/menus/exclude.html
<html>
<body onLoad="javascript:_gaq.push(['_setVar','test_value']);">
    <h2> You've been excluded from Google Analytics.</h2>
</body>
</html>

menuwatch/templates/menus/getready.html
{% extends "menus/base.html" %}

{% block body %}
    <div class="container">
        <h1 class="lato text-center">
            <h3 class="lato">You're almost ready. Check your email for a sign-up link, and get ready for your next-level dining experience!</h3>
        </h1>
    </div>
{% endblock %}

{% block footer_scripts %}

{% endblock %}

menuwatch/templates/menus/onboard.html
{% extends "menus/base.html" %}
{% load user_agents %}

{% block body %}
    <div class="container">
        <h1 class="lato text-center">Hi, {{user.first_name}}! &nbsp;What looks good?</h1>
        <h3 class="lato text-center">Add some foods to get your account started.</h2>
        <table id="onboard-table">
            {% for item in popular %}
                <tr>
                    <td><h3 class="lato popular-item">{{ item.name }}</h3></td>
                    {% if user in item.watchers %}
                        <td class="row-icon large api delete" data="{{ item.pk }}"><i class="icon-remove icon-2x"></i></td>
                    {% else %}
                        <td class="row-icon large api add" data="{{ item.pk }}"><i class="icon-plus icon-2x"></i></td>
                    {% endif %}
                </tr>
            {% endfor %}
        </table>
        <a class="cta-link" href="/browse">
            <div class="cta active-button"><p class="lato cta-text unhighlightable">CONTINUE</p><i class="icon-chevron-right"></i></div>
        </a>
    </div>
{% endblock %}

{% block footer_scripts %}
    {% include 'menus/api.html' %}
{% endblock %}

menuwatch/templates/menus/payment.html
{% extends "menus/base.html" %}

{% block body %}
    <div class="container">
        <a class="logo-bg" href="/">{% include "menus/includes/logo.html" %}</a>
        <form action="/payment" method="post">{% csrf_token %}</form>
    </div>
{% endblock %}


{% block footer_scripts_nocompress %}
    <script src="https://checkout.stripe.com/v2/checkout.js"></script>
{% endblock %}
{% block footer_scripts %}
    <script>$(".navbar").addClass("invisible");</script>
    <script>
        $(document).ready(function(){
            var token = function(res){
                var $input = $('<input type=hidden name=stripeToken />').val(res.id);
                $('form').append($input).submit();
            };

            StripeCheckout.open({
                key:         'pk_live_XD4tFdJYSAZ7AgjbvWdUDMkP',
                address:     false,
                amount:      299,
                currency:    'usd',
                name:        'Menuwatch',
                description: 'Account upgrade',
                panelLabel:  'Upgrade to Pro: ',
                image:       '{{ STATIC_URL }}img/med_logo.png',
                token:       token
            });

            return false;
        });
    </script>
{% endblock %}

menuwatch/templates/menus/unsubscribe.html
{% extends "menus/base.html" %}

{% block body %}
    <div class="container">
        <h1 class="lato bold">
            We're sorry to see you go...
        </h1>
        <h2 class="lato lead">
            But you've now been removed from all Menuwatch alerts. Goodbye!
        </h2>
    </div>
{% endblock %}    

menuwatch/templates/menus/verify.html
{% extends "menus/base.html" %}

{% block body %}
    <div class="container" style="max-width:600px">
        <h1 class="lato bold text-center">Almost there.</h1>
        <br/>
        <h3 class="lato text-center">
            We've sent you a confirmation email with a link to get your account set up. Once you've got it, you'll be ready to <a href="/login">get started!</a>
        </h3>
        <a class="about-header" href="/">{% include "menus/includes/logo.html" %}</a>
    </div>
{% endblock %}